name: Selenium Non Docker Test

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install system dependencies for Chrome and ChromeDriver
      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libxss1 \
            libappindicator3-1 \
            libgdk-pixbuf2.0-0 \
            libnss3 \
            libatk-bridge2.0-0 \
            libnspr4 \
            libasound2 \
            libatk1.0-0 \
            libcups2 \
            wget

      # Step 4: Install Chrome (latest stable version)
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y

      # Step 5: Install WebDriver Manager and Selenium
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager pytest

      # Step 6: Run the tests
      - name: Run tests
        run: |
          pytest test_selenium.py  # Adjust the test file name as needed
