name: Test (single)

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    name: Selenium Test
    runs-on: ubuntu-latest

    container: ubuntu
    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}
        ports: 
          - 4444:4444
          - 7900:7900
        options: --shm-size=2gb

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          apt-get update -y  # Ensure the system is up to date
          apt-get install -y python3 python3-pip curl -y  # Install python and pip if not present
          python3 -m pip install --no-cache-dir --upgrade pip  # Upgrade pip
          python3 -m pip install selenium pytest webdriver-manager

      - name: Wait for Selenium to be ready
        run: |
          echo "Waiting for Selenium to be ready on selenium:4444..."
          for i in {1..2}; do  # Increase retries to 30
            curl -s http://selenium:4444/wd/hub | grep '"ready":true' && echo "Selenium is ready" && break
            echo "Waiting for Selenium..."
            sleep 5
          done

      - name: Run Selenium test
        env:
          BROWSER: ${{ github.event.inputs.browser }}
        run: |
          pytest -v test_selenium.py  # Run tests in test_selenium.py explicitly

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/
